// Pure helpers for the photo-sourcing seed.sql roundtrip (TT-54).
// Kept here (rather than in scripts/) so vitest can cover them.
//
// The PHOTO-SOURCING-CREDITS markers are the contract between
// scripts/photo-sourcing/{apply,export-seed}.ts and supabase/seed.sql.
// Both scripts replace whatever is between the markers; nothing
// outside should touch the block by hand.

export const SEED_BEGIN_MARKER = "-- BEGIN PHOTO-SOURCING-CREDITS";
export const SEED_END_MARKER = "-- END PHOTO-SOURCING-CREDITS";

export interface SeedRow {
  slug: string;
  image_key: string;
  image_etag: string | null;
  image_credit_text: string | null;
  image_credit_link: string | null;
  image_license_short: string | null;
  image_license_url: string | null;
  image_source_url: string | null;
}

function sql(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

export function buildUpdateStatement(table: string, row: SeedRow): string {
  const set = [
    `image_key = ${sql(row.image_key)}`,
    `image_etag = ${sql(row.image_etag)}`,
    `image_credit_text = ${sql(row.image_credit_text)}`,
    `image_credit_link = ${sql(row.image_credit_link)}`,
    `image_license_short = ${sql(row.image_license_short)}`,
    `image_license_url = ${sql(row.image_license_url)}`,
    `image_source_url = ${sql(row.image_source_url)}`,
  ].join(",\n  ");
  return `UPDATE ${table} SET\n  ${set}\nWHERE slug = ${sql(row.slug)};`;
}

// Build the marked block content. Sort each table's rows by slug
// before calling so the output is byte-stable for a given DB state
// (export-seed relies on this for its no-op detection).
export function buildSeedBlock(input: {
  players: SeedRow[];
  equipment: SeedRow[];
}): string {
  const lines: string[] = [
    SEED_BEGIN_MARKER,
    "-- Auto-generated by scripts/photo-sourcing/{apply,export-seed}.ts.",
    "-- Do not edit by hand — re-run `npm run images:export-seed` (or",
    "-- `npm run sourcing:apply` for players) to refresh this block.",
    "",
  ];

  if (input.players.length > 0) {
    lines.push("-- players");
    for (const row of input.players) {
      lines.push(buildUpdateStatement("players", row));
    }
    lines.push("");
  }

  if (input.equipment.length > 0) {
    lines.push("-- equipment");
    for (const row of input.equipment) {
      lines.push(buildUpdateStatement("equipment", row));
    }
    lines.push("");
  }

  lines.push(SEED_END_MARKER);
  return lines.join("\n");
}

// Replace the PHOTO-SOURCING-CREDITS block in `seed` with `block`.
// Throws when the markers are missing — refusing to silently append
// guards against accidentally appending duplicate blocks at EOF.
export function spliceBlock(seed: string, block: string): string {
  const begin = seed.indexOf(SEED_BEGIN_MARKER);
  const end = seed.indexOf(SEED_END_MARKER);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `Markers not found in supabase/seed.sql. Expected:\n  ${SEED_BEGIN_MARKER}\n  ${SEED_END_MARKER}`
    );
  }
  const before = seed.slice(0, begin);
  const after = seed.slice(end + SEED_END_MARKER.length);
  return before + block + after;
}
