name = "app"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Local dev settings
[env.dev.vars]
ENVIRONMENT = "development"
