name = "tt-reviews"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Static files will be served from the app itself

# Local dev settings
[env.dev.vars]
ENVIRONMENT = "development"