-- Generated by scripts/photo-sourcing/apply.ts. Do not edit by hand.
-- Re-run `node --experimental-strip-types scripts/photo-sourcing/apply.ts`
-- to regenerate. See TT-36.

-- players
UPDATE players SET
  image_key = 'player/adriana-diaz/seed.webp',
  image_etag = '311d5e31a8b2',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=115009'
WHERE slug = 'adriana-diaz';
UPDATE players SET
  image_key = 'player/alexis-lebrun/seed.webp',
  image_etag = 'cd8ad04f3212',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=132992'
WHERE slug = 'alexis-lebrun';
UPDATE players SET
  image_key = 'player/an-jaehyun/seed.webp',
  image_etag = '48a6b9683088',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121514'
WHERE slug = 'an-jaehyun';
UPDATE players SET
  image_key = 'player/anders-lind/seed.webp',
  image_etag = '83030cea181c',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=115029'
WHERE slug = 'anders-lind';
UPDATE players SET
  image_key = 'player/anton-kallberg/seed.webp',
  image_etag = '5af9a8eab793',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=116853'
WHERE slug = 'anton-kallberg';
UPDATE players SET
  image_key = 'player/benedikt-duda/seed.webp',
  image_etag = '886ddb148980',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=116620'
WHERE slug = 'benedikt-duda';
UPDATE players SET
  image_key = 'player/bernadette-szocs/seed.webp',
  image_etag = 'f854284701c6',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=111012'
WHERE slug = 'bernadette-szocs';
UPDATE players SET
  image_key = 'player/bruna-takahashi/seed.webp',
  image_etag = '9dc3b3393991',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121623'
WHERE slug = 'bruna-takahashi';
UPDATE players SET
  image_key = 'player/chen-xingtong/seed.webp',
  image_etag = 'a249c6f76778',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121403'
WHERE slug = 'chen-xingtong';
UPDATE players SET
  image_key = 'player/chen-yi/seed.webp',
  image_etag = '83389d7b9fc6',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=132132'
WHERE slug = 'chen-yi';
UPDATE players SET
  image_key = 'player/cheng-i-ching/seed.webp',
  image_etag = '9a99e011272c',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=110797'
WHERE slug = 'cheng-i-ching';
UPDATE players SET
  image_key = 'player/dang-qiu/seed.webp',
  image_etag = '749952fbe12f',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=114715'
WHERE slug = 'dang-qiu';
UPDATE players SET
  image_key = 'player/darko-jorgic/seed.webp',
  image_etag = '5f85e3dea261',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=118927'
WHERE slug = 'darko-jorgic';
UPDATE players SET
  image_key = 'player/dimitrij-ovtcharov/seed.webp',
  image_etag = 'fd5c0c08cae1',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=107028'
WHERE slug = 'dimitrij-ovtcharov';
UPDATE players SET
  image_key = 'player/felix-lebrun/seed.webp',
  image_etag = '0bf551ef2aaa',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=135977'
WHERE slug = 'felix-lebrun';
UPDATE players SET
  image_key = 'player/hana-goda/seed.webp',
  image_etag = 'e806ae8456a4',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=131335'
WHERE slug = 'hana-goda';
UPDATE players SET
  image_key = 'player/he-zhuojia/seed.webp',
  image_etag = 'c1e812ae76e8',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=119730'
WHERE slug = 'he-zhuojia';
UPDATE players SET
  image_key = 'player/hina-hayata/seed.webp',
  image_etag = '95d988cb0f31',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=123672'
WHERE slug = 'hina-hayata';
UPDATE players SET
  image_key = 'player/honoka-hashimoto/seed.webp',
  image_etag = 'b8f7fc44c646',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=133000'
WHERE slug = 'honoka-hashimoto';
UPDATE players SET
  image_key = 'player/hugo-calderano/seed.webp',
  image_etag = '702bf521e151',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=115641'
WHERE slug = 'hugo-calderano';
UPDATE players SET
  image_key = 'player/jang-woojin/seed.webp',
  image_etag = '5f5292361197',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=114936'
WHERE slug = 'jang-woojin';
UPDATE players SET
  image_key = 'player/jonathan-groth/seed.webp',
  image_etag = 'e7ef8ac04dd0',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=112409'
WHERE slug = 'jonathan-groth';
UPDATE players SET
  image_key = 'player/kao-cheng-jui/seed.webp',
  image_etag = '4cc7ab25bce1',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=132824'
WHERE slug = 'kao-cheng-jui';
UPDATE players SET
  image_key = 'player/kuai-man/seed.webp',
  image_etag = '158f11a3a191',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=135049'
WHERE slug = 'kuai-man';
UPDATE players SET
  image_key = 'player/liang-jingkun/seed.webp',
  image_etag = '159aaa80efcc',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=119588'
WHERE slug = 'liang-jingkun';
UPDATE players SET
  image_key = 'player/lin-gaoyuan/seed.webp',
  image_etag = '3fde13df8696',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=115910'
WHERE slug = 'lin-gaoyuan';
UPDATE players SET
  image_key = 'player/lin-shidong/seed.webp',
  image_etag = '4be2de17a866',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=137237'
WHERE slug = 'lin-shidong';
UPDATE players SET
  image_key = 'player/lin-yun-ju/seed.webp',
  image_etag = 'eb17bc0fa67b',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121582'
WHERE slug = 'lin-yun-ju';
UPDATE players SET
  image_key = 'player/mima-ito/seed.webp',
  image_etag = 'adadf3f9d8bf',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=117821'
WHERE slug = 'mima-ito';
UPDATE players SET
  image_key = 'player/miu-hirano/seed.webp',
  image_etag = 'e3d7f0b6d2ee',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=117820'
WHERE slug = 'miu-hirano';
UPDATE players SET
  image_key = 'player/miwa-harimoto/seed.webp',
  image_etag = '8ba9885d0be3',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=136711'
WHERE slug = 'miwa-harimoto';
UPDATE players SET
  image_key = 'player/miyuu-kihara/seed.webp',
  image_etag = '02a456d09ec8',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=131036'
WHERE slug = 'miyuu-kihara';
UPDATE players SET
  image_key = 'player/oh-junsung/seed.webp',
  image_etag = '5db30b656763',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=135367'
WHERE slug = 'oh-junsung';
UPDATE players SET
  image_key = 'player/omar-assar/seed.webp',
  image_etag = '954ed4a781fb',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=100696'
WHERE slug = 'omar-assar';
UPDATE players SET
  image_key = 'player/patrick-franziska/seed.webp',
  image_etag = '1db255a8a94a',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=102832'
WHERE slug = 'patrick-franziska';
UPDATE players SET
  image_key = 'player/prithika-pavade/seed.webp',
  image_etag = '8082ec44e112',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=131100'
WHERE slug = 'prithika-pavade';
UPDATE players SET
  image_key = 'player/qian-tianyi/seed.webp',
  image_etag = 'ea9181a6da24',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=119797'
WHERE slug = 'qian-tianyi';
UPDATE players SET
  image_key = 'player/satsuki-odo/seed.webp',
  image_etag = '19796f0e2171',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=133405'
WHERE slug = 'satsuki-odo';
UPDATE players SET
  image_key = 'player/shi-xunyao/seed.webp',
  image_etag = 'ee45e07b6249',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=123120'
WHERE slug = 'shi-xunyao';
UPDATE players SET
  image_key = 'player/shin-yubin/seed.webp',
  image_etag = '24dde722266b',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=123977'
WHERE slug = 'shin-yubin';
UPDATE players SET
  image_key = 'player/sofia-polcanova/seed.webp',
  image_etag = '6a72989ef9b9',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=107477'
WHERE slug = 'sofia-polcanova';
UPDATE players SET
  image_key = 'player/sora-matsushima/seed.webp',
  image_etag = '8d2726d79dbd',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=135996'
WHERE slug = 'sora-matsushima';
UPDATE players SET
  image_key = 'player/sun-yingsha/seed.webp',
  image_etag = 'd1d2a301b2a1',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=131163'
WHERE slug = 'sun-yingsha';
UPDATE players SET
  image_key = 'player/tomokazu-harimoto/seed.webp',
  image_etag = '8c7ae849d893',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=123980'
WHERE slug = 'tomokazu-harimoto';
UPDATE players SET
  image_key = 'player/truls-moregard/seed.webp',
  image_etag = '49e052e5f159',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=122044'
WHERE slug = 'truls-moregard';
UPDATE players SET
  image_key = 'player/wang-chuqin/seed.webp',
  image_etag = '5368d75f4ea0',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121558'
WHERE slug = 'wang-chuqin';
UPDATE players SET
  image_key = 'player/wang-manyu/seed.webp',
  image_etag = 'f8dad65a4390',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=121411'
WHERE slug = 'wang-manyu';
UPDATE players SET
  image_key = 'player/wang-yidi/seed.webp',
  image_etag = 'e8fc9ee0069f',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=124110'
WHERE slug = 'wang-yidi';
UPDATE players SET
  image_key = 'player/xiang-peng/seed.webp',
  image_etag = '6f928afef9bb',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=135888'
WHERE slug = 'xiang-peng';
UPDATE players SET
  image_key = 'player/zhu-yuling/seed.webp',
  image_etag = '8f12e000ecf1',
  image_credit_text = 'World Table Tennis',
  image_credit_link = NULL,
  image_license_short = NULL,
  image_license_url = NULL,
  image_source_url = 'https://www.worldtabletennis.com/playerDescription?playerId=117332'
WHERE slug = 'zhu-yuling';
