// Pure helpers for the spec-sourcing seed.sql roundtrip (TT-151,
// closes TT-78). Mirrors app/lib/photo-sourcing/seed-block.ts in
// shape — kept under app/ rather than scripts/ so vitest can cover
// the splice + build logic.
//
// The SPEC-SOURCING markers are the contract between
// scripts/spec-sourcing/export-seed.ts and supabase/seed.sql. Both
// the script and any future apply-style tooling replace whatever sits
// between the markers; nothing outside should touch the block by hand.

export const SEED_BEGIN_MARKER = "-- BEGIN SPEC-SOURCING";
export const SEED_END_MARKER = "-- END SPEC-SOURCING";

export interface SpecSeedRow {
  slug: string;
  specifications: Record<string, unknown>;
  description: string | null;
  per_field_source: Record<string, string>;
}

function sql(value: string | null): string {
  if (value === null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function uniqueSources(map: Record<string, string>): string[] {
  const set = new Set<string>();
  for (const v of Object.values(map ?? {})) {
    if (typeof v === "string" && v.length > 0) set.add(v);
  }
  return [...set].sort();
}

// Stable JSON serialisation: sort keys so the output is byte-stable
// for a given DB state (export-seed relies on this for its no-op
// detection). Recursive — applies inside nested objects too (e.g.
// hardness range carries min/max in a stable order).
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(",")}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>).sort(
    ([a], [b]) => a.localeCompare(b)
  );
  return `{${entries
    .map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`)
    .join(",")}}`;
}

export function buildUpdateStatement(row: SpecSeedRow): string {
  const specsJson = stableStringify(row.specifications ?? {});
  const lines = [
    "UPDATE equipment SET",
    `  specifications = ${sql(specsJson)}::jsonb,`,
    `  description = ${sql(row.description)}`,
    `WHERE slug = ${sql(row.slug)};`,
  ];
  const sources = uniqueSources(row.per_field_source ?? {});
  if (sources.length > 0) {
    lines.push(`-- src: ${sources.join(", ")}`);
  }
  return lines.join("\n");
}

// Build the marked block content. Sort `rows` by slug before calling
// so the output is byte-stable.
export function buildSeedBlock(rows: SpecSeedRow[]): string {
  const lines: string[] = [
    SEED_BEGIN_MARKER,
    "-- Auto-generated by scripts/spec-sourcing/export-seed.ts (TT-151).",
    "-- Do not edit by hand — re-run `npm run sourcing:export-specs` to",
    "-- refresh this block. Each UPDATE is followed by a -- src: comment",
    "-- listing the source URLs the merge picked from.",
    "",
  ];
  for (const row of rows) {
    lines.push(buildUpdateStatement(row));
    lines.push("");
  }
  lines.push(SEED_END_MARKER);
  return lines.join("\n");
}

// Replace the SPEC-SOURCING block in `seed` with `block`. Creates the
// markers at the end of the file on first run (the photo-sourcing
// equivalent throws here, but the brief explicitly asks export-seed
// to bootstrap the markers — TT-78 has been waiting on this script,
// so the seed.sql doesn't yet carry the SPEC-SOURCING block).
export function spliceBlock(seed: string, block: string): string {
  const begin = seed.indexOf(SEED_BEGIN_MARKER);
  const end = seed.indexOf(SEED_END_MARKER);

  if (begin === -1 && end === -1) {
    const trailingNewline = seed.endsWith("\n") ? "" : "\n";
    return seed + trailingNewline + "\n" + block + "\n";
  }
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `Markers in supabase/seed.sql are out of order or partially missing. Expected:\n  ${SEED_BEGIN_MARKER}\n  ${SEED_END_MARKER}`
    );
  }

  const before = seed.slice(0, begin);
  const after = seed.slice(end + SEED_END_MARKER.length);
  return before + block + after;
}
