import { describe, expect, it } from "vitest";

import {
  SEED_BEGIN_MARKER,
  SEED_END_MARKER,
  buildSeedBlock,
  buildUpdateStatement,
  spliceBlock,
  type SpecSeedRow,
} from "../seed-block";

const VISCARIA: SpecSeedRow = {
  slug: "butterfly-viscaria",
  specifications: {
    weight: 89,
    plies_wood: 5,
    plies_composite: 2,
    composite_material: "Arylate Carbon",
  },
  description: "Legendary all-round blade.",
  per_field_source: {
    weight: "https://en.butterfly.tt/viscaria.html",
    plies_wood: "https://en.butterfly.tt/viscaria.html",
    plies_composite: "https://en.butterfly.tt/viscaria.html",
    composite_material: "https://revspin.net/blade/butterfly-viscaria.html",
    description: "https://en.butterfly.tt/viscaria.html",
  },
};

describe("buildUpdateStatement", () => {
  it("emits a JSONB-cast UPDATE with description and slug-keyed WHERE", () => {
    const sql = buildUpdateStatement(VISCARIA);
    expect(sql).toContain("UPDATE equipment SET");
    expect(sql).toContain("specifications = '");
    expect(sql).toContain("'::jsonb");
    expect(sql).toContain("description = 'Legendary all-round blade.'");
    expect(sql).toContain("WHERE slug = 'butterfly-viscaria';");
  });

  it("appends a -- src: comment listing every unique source URL sorted", () => {
    const sql = buildUpdateStatement(VISCARIA);
    expect(sql).toMatch(
      /^-- src: https:\/\/en\.butterfly\.tt\/viscaria\.html, https:\/\/revspin\.net\/blade\/butterfly-viscaria\.html$/m
    );
  });

  it("omits the -- src comment when per_field_source is empty", () => {
    const sql = buildUpdateStatement({
      ...VISCARIA,
      per_field_source: {},
    });
    expect(sql).not.toContain("-- src:");
  });

  it("renders NULL for a null description", () => {
    const sql = buildUpdateStatement({ ...VISCARIA, description: null });
    expect(sql).toContain("description = NULL");
  });

  it("escapes single quotes in description and slug", () => {
    const sql = buildUpdateStatement({
      ...VISCARIA,
      slug: "o'brien-blade",
      description: "Player's choice — 'fast'.",
    });
    expect(sql).toContain("'o''brien-blade'");
    expect(sql).toContain("'Player''s choice — ''fast''.'");
  });

  it("renders specs JSONB with stable key order regardless of input order", () => {
    const a = buildUpdateStatement({
      ...VISCARIA,
      specifications: { weight: 89, plies_wood: 5 },
    });
    const b = buildUpdateStatement({
      ...VISCARIA,
      specifications: { plies_wood: 5, weight: 89 },
    });
    expect(a).toBe(b);
  });

  it("handles nested object values (hardness range) with stable inner ordering", () => {
    const sql = buildUpdateStatement({
      ...VISCARIA,
      specifications: { hardness: { min: 40, max: 42 } },
    });
    // min listed before max alphabetically — stable.
    expect(sql).toContain('"hardness":{"max":42,"min":40}');
  });
});

describe("buildSeedBlock", () => {
  it("wraps rows with begin and end markers", () => {
    const block = buildSeedBlock([VISCARIA]);
    expect(block.startsWith(SEED_BEGIN_MARKER)).toBe(true);
    expect(block.endsWith(SEED_END_MARKER)).toBe(true);
  });

  it("emits an empty marker pair when no rows are passed", () => {
    const block = buildSeedBlock([]);
    expect(block).toContain(SEED_BEGIN_MARKER);
    expect(block).toContain(SEED_END_MARKER);
    expect(block).not.toContain("UPDATE equipment SET");
  });

  it("includes a generated-by comment so editors don't hand-edit the block", () => {
    const block = buildSeedBlock([VISCARIA]);
    expect(block).toMatch(/Auto-generated by scripts\/spec-sourcing/);
  });
});

describe("spliceBlock", () => {
  const SEED_BEFORE = "-- preamble\nSELECT 1;\n";
  const SEED_AFTER = "\n-- trailing\nSELECT 2;\n";

  it("creates markers at end-of-file on first run when none exist", () => {
    const block = buildSeedBlock([VISCARIA]);
    const next = spliceBlock(SEED_BEFORE, block);
    expect(next).toContain(SEED_BEGIN_MARKER);
    expect(next).toContain(SEED_END_MARKER);
    expect(next.startsWith(SEED_BEFORE)).toBe(true);
  });

  it("replaces an existing block between the markers", () => {
    const block = buildSeedBlock([VISCARIA]);
    const seed = SEED_BEFORE + block + SEED_AFTER;
    const block2 = buildSeedBlock([
      { ...VISCARIA, slug: "stiga-allround-classic" },
    ]);
    const next = spliceBlock(seed, block2);
    expect(next).toContain("'stiga-allround-classic'");
    expect(next).not.toContain("'butterfly-viscaria'");
    expect(next.startsWith(SEED_BEFORE)).toBe(true);
    expect(next.endsWith(SEED_AFTER)).toBe(true);
  });

  it("is idempotent: re-splicing the same block produces a byte-identical seed", () => {
    const block = buildSeedBlock([VISCARIA]);
    const once = spliceBlock(SEED_BEFORE, block);
    const twice = spliceBlock(once, block);
    expect(twice).toBe(once);
  });

  it("throws when only one of the two markers is present", () => {
    const block = buildSeedBlock([VISCARIA]);
    const corrupted = `${SEED_BEFORE}${SEED_BEGIN_MARKER}\n some rows ${SEED_AFTER}`;
    expect(() => spliceBlock(corrupted, block)).toThrow(
      /out of order or partially missing/
    );
  });

  it("throws when end marker appears before begin marker", () => {
    const block = buildSeedBlock([VISCARIA]);
    const flipped = `${SEED_END_MARKER}\n${SEED_BEGIN_MARKER}\n`;
    expect(() => spliceBlock(flipped, block)).toThrow(/out of order/);
  });
});
