name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run code quality checks
        run: |
          echo "🔍 Running code quality checks..."
          npm run check

      - name: Run Discord tests
        run: |
          echo "🧪 Running Discord integration tests..."
          npm run test:discord

      - name: Run all tests
        run: |
          echo "🧪 Running all tests..."
          npm test
